import { test, expect } from '@playwright/test'
test('cart CRUD, persistence and simulated checkout', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Agregar al carrito', exact: true }).first().click()
  await page.getByRole('button', { name: 'Carrito 1', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('heading', { name: 'Nocta Cap White' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Sumar Nocta Cap White' }).click()
  await expect(dialog.getByRole('heading', { name: 'Tu carrito (2)' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Carrito 2', exact: true }).click()
  await dialog.getByRole('button', { name: 'Restar Nocta Cap White' }).click()
  await dialog.getByRole('button', { name: 'Eliminar Nocta Cap White del carrito' }).click()
  await expect(dialog.getByText('Todavía no agregaste productos.')).toBeVisible()
  await dialog.getByRole('button', { name: 'Explorar colección' }).click()
  await page.getByRole('button', { name: 'Agregar al carrito', exact: true }).first().click()
  await page.getByRole('button', { name: 'Carrito 1', exact: true }).click()
  await dialog.getByRole('button', { name: 'Confirmar pedido simulado' }).click()
  await expect(dialog.getByText('¡Pedido simulado confirmado!')).toBeVisible()
  await dialog.getByRole('button', { name: 'Seguir explorando' }).click()
  await expect(page.getByRole('button', { name: 'Carrito 0', exact: true })).toBeVisible()
})
test('catalog ignores legacy edits while preserving favorites and the cart', async ({ page }) => {
  await page.addInitScript(() => {
    if (!localStorage.getItem('elite-club-v1')) localStorage.setItem('elite-club-v1', JSON.stringify({
      products: [{ id: 'fake', name: 'Producto modificado', brand: 'OTRA', size: 'M', type: 'REMERA', image: '/placeholder.svg' }],
      cart: [{ id: 'elite-2', quantity: 2 }], favorites: ['elite-2'],
    }))
  })
  await page.goto('/')
  await expect(page.getByRole('button', { name: /Gestionar catálogo|Nuevo producto|Editar|Eliminar producto/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Ver Nocta Cap', exact: true })).toBeVisible()
  await expect(page.getByText('Producto modificado')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Carrito 2', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Ver favoritos', exact: true }).click()
  await expect(page.locator('.product-card')).toHaveCount(1)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Carrito 2', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Ver favoritos', exact: true }).click()
  await expect(page.locator('.product-card')).toHaveCount(1)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('elite-club-v1')).products)).toBeUndefined()
})
test('mobile layout and product images', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.product-card')).toHaveCount(12)
  await page.locator('#catalogo').scrollIntoViewIfNeeded()
  await expect.poll(() => page.locator('.product-card img').first().evaluate(img => img.complete && img.naturalWidth > 0)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
})
